language: ruby

notifications:
  email:
    recipients:  
      - kou@clear-code.com
      - ongaeshi0621@gmail.com
      
rvm:
  # - 1.8.7
  # - 1.9.3
  # - 2.0.0
  - 2.1.9
  - 2.2.5
  - 2.3.1

sudo: required
before_install:
  - curl --silent --location https://github.com/groonga/groonga/raw/master/data/travis/setup.sh | sh
  - gem update bundler
